name: actions-example
# on: [push]
on: 
  push:
  pull_request:
    types: [closed, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: vari√°veis de ambiente do github
        run: |
          echo $GITHUB_ACTION_PATH
          echo $GITHUB_ACTOR
          echo $GITHUB_REPOSITORY
      - name: simples js action
        id: greet
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: emily
      - name: logando
        run: echo "${{ steps.greet.outputs.time }}"